name: Master FFL Layers

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      component:
        type: choice
        description: Choose Layer
        options: 
        - DB-LAYER
        default: DB-LAYER
        required: true
      version:
        type: choice
        description: Choose Version
        options: 
        - PATCH
        - MINOR
        - MAJOR
        default: PATCH
        required: true
  release:    
    types: [created]
env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  LAYERS_PATH: $(echo "${{ github.event.inputs.component }}" | tr '[:upper:]' '[:lower:]')
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.region }}
  AWS_WAF_CAPTCHA_KEY: ${{ secrets.AWS_WAF_CAPTCHA_KEY }}

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    environment: PROD
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_SECRET }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@masterffl'
      - run: git config --global user.name 'masterFFL'
      - run: git config --global user.email 'release@masterFFL.com'

      - name: PATCH VERSIONING
        if: "${{ github.event.inputs.version == 'PATCH' }}"
        run: | 
             cd "${{env.LAYERS_PATH}}" && npm version patch -m "Upgrade to %s"

      - name: MINOR VERSIONING
        if: "${{ github.event.inputs.version =='MINOR' }}"
        run: cd "${{env.LAYERS_PATH}}" && npm version minor -m "Upgrade to %s"

      - name: MAJOR VERSIONING
        if: "${{ github.event.inputs.version == 'MAJOR' }}"
        run: cd "${{env.LAYERS_PATH}}" && npm version major -m "Upgrade to %s"

      - name: Update Package json file
        run: cd "${{env.LAYERS_PATH}}" && git status && git add package.json && git commit -m "package.json" && git push &&  git diff HEAD^ HEAD

      - name: Build & Publish Component
        run: cd "${{env.LAYERS_PATH}}" && npm install && npm run build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          libs_bucket: ${{ secrets.LIBS_BUCKET }}